import type { Campaign, CampaignCategory, Donor } from "@/types/campaign";

export const CATEGORIES: CampaignCategory[] = [
  "Flood Relief",
  "Education",
  "Healthcare",
  "Food & Nutrition",
  "Orphan Care",
  "Shelter",
  "Emergency Aid",
  "Water & Sanitation",
  "Mosque & Madrassah",
  "Environment",
];

export const CAMPAIGNS: Campaign[] = [
  {
    id: "flood-relief-sindh",
    type: "ngo",
    title: "Flood Relief for 50 Families in Sindh",
    organizer: "Al-Khidmat Foundation",
    organizerNote: "Verified NGO",
    verified: true,
    verificationLevel: "ngo",
    badges: ["urgent", "trending"],
    category: "Flood Relief",
    location: "Sindh, Pakistan",
    description:
      "Emergency shelter, clean water and food packs for 50 families displaced by the recent floods.",
    zakatEligible: true,
    story: [
      "The monsoon floods have submerged entire villages across rural Sindh, leaving thousands without shelter, clean water, or food. 50 families in the worst-hit areas have lost everything — their homes, livestock, and crops.",
      "Al-Khidmat Foundation teams are already on the ground. Your donation funds emergency tents, clean drinking water, and a month of food rations for each family while they begin to rebuild their lives.",
      "Every contribution is released against verified milestones — campaign runners submit receipts and photos before any funds move, so you can see exactly how your Zakat and Sadaqah reach the families who need it most.",
    ],
    image: "/campaigns/flood-relief.jpg",
    gradient: "from-emerald-500 via-teal-600 to-cyan-700",
    raised: 875_000,
    goal: 1_250_000,
    supporters: 234,
    daysLeft: 12,
    milestones: [
      {
        id: "m1",
        label: "Emergency relief distributed",
        note: "Ration packs, water & medicine for all 50 families",
        amountReleased: 350_000,
        reached: true,
        date: "Jun 8, 2026",
      },
      {
        id: "m2",
        label: "Temporary shelter installed",
        note: "Tarpaulin tents and bedding for every household",
        amountReleased: 250_000,
        reached: true,
        date: "Jun 12, 2026",
      },
      {
        id: "m3",
        label: "Permanent shelter construction",
        note: "Materials and labour — 20 homes to be rebuilt",
        reached: false,
      },
    ],
    updates: [
      {
        id: "u1",
        date: "Jun 8, 2026",
        title: "Emergency ration packs delivered to all 50 families",
        description:
          "Our field team reached all 50 flood-affected families in Dadu district within 48 hours. Each family received a 20 kg flour bag, 5 L cooking oil, lentils, rice, dates and a basic medicine kit. Every distribution was video recorded and cross-checked against our beneficiary register.",
        amountSpent: 120_000,
        receiptCount: 3,
        photoCount: 8,
        status: "approved",
        photoGradients: [
          "from-cyan-400 to-teal-600",
          "from-emerald-400 to-green-600",
          "from-teal-300 to-cyan-500",
        ],
      },
      {
        id: "u2",
        date: "Jun 12, 2026",
        title: "Tarpaulin tents and bedding installed for all families",
        description:
          "50 waterproof tarpaulin tents, 100 sleeping mats and 150 blankets have been installed across three sites. Families now have a dry, safe shelter while they wait for permanent homes to be rebuilt. All materials were procured from a local supplier and receipts are attached.",
        amountSpent: 230_000,
        receiptCount: 2,
        photoCount: 12,
        status: "approved",
        photoGradients: [
          "from-sky-400 to-blue-600",
          "from-indigo-400 to-violet-600",
          "from-cyan-300 to-sky-500",
          "from-blue-400 to-indigo-600",
        ],
      },
      {
        id: "u3",
        date: "Jun 15, 2026",
        title: "Clean water supply and purification tablets arranged",
        description:
          "Procured a three-month supply of water purification tablets for all families. Arranged daily water tanker deliveries to both clusters. Water quality tested by our health volunteer and cleared safe for drinking and cooking.",
        amountSpent: 50_000,
        receiptCount: 1,
        photoCount: 4,
        status: "approved",
        photoGradients: [
          "from-teal-400 to-emerald-600",
          "from-cyan-400 to-teal-600",
        ],
      },
    ],
  },
  {
    id: "school-fees-thar",
    type: "ngo",
    title: "Send 120 Girls Back to School in Thar",
    organizer: "The Citizens Foundation",
    organizerNote: "Verified NGO",
    verified: true,
    verificationLevel: "ngo",
    badges: ["verified"],
    category: "Education",
    location: "Tharparkar, Pakistan",
    description:
      "Tuition, uniforms and books to keep 120 girls in school for a full academic year.",
    zakatEligible: true,
    recurringEnabled: true,
    monthlyImpact: "Keeps one girl in school for a whole month",
    story: [
      "In Tharparkar, girls are often the first to be pulled out of school when money runs short. 120 bright, determined girls are at risk of dropping out this year.",
      "Your support covers a full year of tuition, uniforms, books and stationery — everything they need to stay in the classroom and keep dreaming big.",
      "Education is the surest path out of poverty. A single year of schooling can change the trajectory of a girl's entire life and her future family.",
    ],
    image: "/campaigns/education-girls.jpg",
    gradient: "from-amber-400 via-orange-500 to-rose-500",
    raised: 410_000,
    goal: 900_000,
    supporters: 156,
    daysLeft: 28,
    milestones: [
      {
        id: "m1",
        label: "School fees paid for all 120 students",
        note: "Annual tuition deposited to each school",
        amountReleased: 250_000,
        reached: true,
        date: "May 20, 2026",
      },
      {
        id: "m2",
        label: "Uniforms and books distributed",
        note: "Local tailors for uniforms, stationery kits",
        amountReleased: 0,
        reached: false,
      },
      {
        id: "m3",
        label: "Mid-year attendance review",
        note: "Proof that all 120 girls are still enrolled",
        reached: false,
      },
    ],
    updates: [
      {
        id: "u1",
        date: "May 20, 2026",
        title: "Annual school fees deposited for all 120 girls",
        description:
          "Fees were deposited directly into the school accounts of all six partner schools in Tharparkar. We shared the bank transfer receipts with Apnaiyat and received confirmation from each school principal. All 120 girls are now enrolled for the full academic year.",
        amountSpent: 250_000,
        receiptCount: 6,
        photoCount: 3,
        status: "approved",
        photoGradients: [
          "from-amber-400 to-orange-600",
          "from-yellow-300 to-amber-500",
        ],
      },
      {
        id: "u2",
        date: "Jun 3, 2026",
        title: "Uniform stitching underway at local tailors",
        description:
          "We have placed orders with three local tailors in Mithi to stitch uniforms for all 120 girls. Using local craftswomen supports the community economy. Estimated completion and distribution by June 20th.",
        receiptCount: 1,
        photoCount: 4,
        status: "pending",
        photoGradients: [
          "from-rose-400 to-pink-600",
          "from-orange-300 to-rose-500",
        ],
      },
    ],
  },
  {
    id: "ayaan-heart-surgery",
    type: "individual",
    title: "Help Baby Ayaan Get His Heart Surgery",
    organizer: "Hira Khan",
    organizerNote: "Mother • Lahore",
    verified: true,
    verificationLevel: "cnic",
    badges: ["urgent"],
    category: "Healthcare",
    location: "Lahore, Pakistan",
    description:
      "My 8-month-old son needs urgent open-heart surgery. We are short of funds and time is running out.",
    zakatEligible: true,
    story: [
      "My son Ayaan was born with a congenital heart defect. At just 8 months old, doctors say he needs open-heart surgery within weeks or his condition will become life-threatening.",
      "We have spent our savings on tests and medicines. The surgery itself is beyond anything we can afford on my husband's modest income.",
      "I am turning to the kindness of strangers as a last hope. Please help me give my baby the chance to grow up. Every rupee brings us closer to his operation.",
    ],
    image: "/campaigns/baby-care.jpg",
    gradient: "from-rose-400 via-pink-500 to-fuchsia-600",
    raised: 1_180_000,
    goal: 1_500_000,
    supporters: 541,
    daysLeft: 6,
    milestones: [
      {
        id: "m1",
        label: "Pre-operative tests completed",
        note: "Echo, blood work and surgical consultation",
        amountReleased: 45_000,
        reached: true,
        date: "Jun 5, 2026",
      },
      {
        id: "m2",
        label: "Surgery scheduled & hospital advance paid",
        note: "Operation booked at Children's Hospital Lahore",
        amountReleased: 700_000,
        reached: true,
        date: "Jun 10, 2026",
      },
      {
        id: "m3",
        label: "Surgery & post-op recovery",
        note: "Remaining funds released on discharge summary",
        reached: false,
      },
    ],
    updates: [
      {
        id: "u1",
        date: "Jun 5, 2026",
        title: "Pre-operative tests completed at Children's Hospital Lahore",
        description:
          "Ayaan completed all pre-operative tests including an echocardiogram, full blood panel and surgical risk assessment. The cardiac surgeon has confirmed he is fit for surgery. All reports and test receipts are attached. JazakAllah khair to every donor — we are almost there.",
        amountSpent: 45_000,
        receiptCount: 4,
        photoCount: 3,
        status: "approved",
        photoGradients: [
          "from-rose-300 to-pink-500",
          "from-pink-400 to-fuchsia-600",
        ],
      },
      {
        id: "u2",
        date: "Jun 10, 2026",
        title: "Surgery confirmed for June 22nd — hospital advance paid",
        description:
          "Surgery is scheduled for June 22nd at Children's Hospital Lahore. The hospital advance of PKR 7,00,000 has been released after Apnaiyat reviewed our booking documents. The receipt and hospital booking letter are attached. Please keep Ayaan and our family in your duas.",
        amountSpent: 700_000,
        receiptCount: 2,
        photoCount: 1,
        status: "approved",
        photoGradients: [
          "from-fuchsia-400 to-rose-600",
        ],
      },
    ],
  },
  {
    id: "ramzan-ration-drive",
    type: "ngo",
    title: "Ramzan Ration Drive — 1,000 Food Packs",
    organizer: "Saylani Welfare Trust",
    organizerNote: "Verified NGO",
    verified: true,
    verificationLevel: "ngo",
    badges: ["trending"],
    category: "Food & Nutrition",
    location: "Karachi, Pakistan",
    description:
      "A month of essential groceries for 1,000 deserving families during Ramzan.",
    zakatEligible: true,
    recurringEnabled: true,
    monthlyImpact: "Feeds one family for an entire month",
    story: [
      "Ramzan is a month of giving, yet for thousands of families in Karachi it is a month of going without. Rising food prices have put basic groceries out of reach.",
      "Each ration pack contains flour, rice, lentils, cooking oil, sugar, dates and tea — enough to feed a family of six for the entire month.",
      "Help us prepare and distribute 1,000 ration packs so no family has to break their fast on an empty table this Ramzan.",
    ],
    image: "/campaigns/ration-packs.jpg",
    gradient: "from-lime-400 via-green-500 to-emerald-600",
    raised: 2_050_000,
    goal: 3_000_000,
    supporters: 803,
    daysLeft: 18,
    milestones: [
      {
        id: "m1",
        label: "Bulk groceries purchased",
        note: "Wholesale purchase from Mandi for 1,000 packs",
        amountReleased: 1_000_000,
        reached: true,
        date: "May 15, 2026",
      },
      {
        id: "m2",
        label: "First 500 packs distributed — Zone 1 (Lyari, Orangi)",
        note: "Distribution complete with beneficiary list",
        amountReleased: 500_000,
        reached: true,
        date: "May 22, 2026",
      },
      {
        id: "m3",
        label: "Remaining 500 packs distributed — Zone 2",
        note: "North Nazimabad and Korangi areas",
        reached: false,
      },
    ],
    updates: [
      {
        id: "u1",
        date: "May 15, 2026",
        title: "1,000 ration packs assembled at central warehouse",
        description:
          "Bulk groceries were procured from the wholesale market in Lyari and packed into 1,000 individual bags at our central warehouse by 80 volunteers. Items per bag: 10 kg flour, 5 kg rice, 2 kg lentils, 2 L cooking oil, 1 kg sugar, 500 g dates and 250 g tea. All supplier receipts attached.",
        amountSpent: 1_000_000,
        receiptCount: 5,
        photoCount: 10,
        status: "approved",
        photoGradients: [
          "from-lime-400 to-green-600",
          "from-green-400 to-emerald-600",
          "from-emerald-300 to-teal-500",
          "from-teal-400 to-green-600",
        ],
      },
      {
        id: "u2",
        date: "May 22, 2026",
        title: "500 families received ration packs in Lyari and Orangi Town",
        description:
          "First distribution phase complete. 500 families in Lyari and Orangi Town collected their packs at two distribution points. Our team verified CNICs against the beneficiary register before handing over each pack. Full signed beneficiary list is on file with Apnaiyat.",
        receiptCount: 0,
        photoCount: 15,
        status: "approved",
        photoGradients: [
          "from-yellow-400 to-orange-600",
          "from-orange-400 to-red-600",
          "from-amber-300 to-yellow-500",
        ],
      },
      {
        id: "u3",
        date: "Jun 2, 2026",
        title: "Second distribution underway — North Nazimabad & Korangi",
        description:
          "We have started the second distribution phase in North Nazimabad and Korangi. 200 of the remaining 500 packs have been handed over so far. Distribution continues through June 5th. Photos from Day 1 attached.",
        amountSpent: 0,
        receiptCount: 0,
        photoCount: 8,
        status: "pending",
        photoGradients: [
          "from-green-400 to-lime-600",
          "from-teal-400 to-cyan-600",
        ],
      },
    ],
  },
  {
    id: "fatima-university",
    type: "individual",
    title: "Fund Fatima's First Year at University",
    organizer: "Fatima Noor",
    organizerNote: "Student • Multan",
    verified: false,
    verificationLevel: "unverified",
    badges: [],
    category: "Education",
    location: "Multan, Pakistan",
    description:
      "I topped my college but can't afford university. Your support can help me become the first graduate in my family.",
    zakatEligible: true,
    story: [
      "I scored 92% in my intermediate exams and earned admission to a top university to study computer science. It is a dream come true — and a dream I cannot afford.",
      "My father is a daily-wage labourer. There is simply no way for my family to cover tuition, hostel and books for even a single semester.",
      "If you help me through my first year, I promise to work part-time and earn scholarships for the rest. I want to be the first graduate in my family and lift us out of poverty.",
    ],
    image: "/campaigns/student.jpg",
    gradient: "from-sky-400 via-blue-500 to-indigo-600",
    raised: 95_000,
    goal: 400_000,
    supporters: 47,
    daysLeft: 34,
    milestones: [
      {
        id: "m1",
        label: "Admission fee paid",
        amountReleased: 35_000,
        reached: true,
        date: "May 28, 2026",
      },
      {
        id: "m2",
        label: "First semester tuition fee",
        amountReleased: 120_000,
        reached: false,
      },
      {
        id: "m3",
        label: "Hostel & books for first year",
        amountReleased: 85_000,
        reached: false,
      },
    ],
    updates: [
      {
        id: "u1",
        date: "May 28, 2026",
        title: "Admission confirmed at NUST — fee receipt attached",
        description:
          "I paid the admission fee using the first release and have officially secured my seat in the BS Computer Science programme at NUST. Alhamdulillah! The university admission letter and fee receipt are both uploaded.",
        amountSpent: 35_000,
        receiptCount: 2,
        photoCount: 3,
        status: "approved",
        photoGradients: [
          "from-sky-400 to-blue-600",
          "from-indigo-400 to-violet-600",
          "from-blue-300 to-sky-500",
        ],
      },
      {
        id: "u2",
        date: "Jun 10, 2026",
        title: "Orientation week complete — classes start next week",
        description:
          "I attended orientation and met my professors and classmates. It still feels unreal that I am here. Classes begin formally next Monday. Sharing my student ID and timetable as proof of enrollment.",
        receiptCount: 1,
        photoCount: 2,
        status: "approved",
        photoGradients: [
          "from-violet-400 to-purple-600",
          "from-sky-300 to-cyan-500",
        ],
      },
    ],
  },
  {
    id: "orphan-care-quetta",
    type: "ngo",
    title: "Sponsor Meals for 200 Orphans in Quetta",
    organizer: "Edhi Foundation",
    organizerNote: "Verified NGO",
    verified: true,
    verificationLevel: "ngo",
    badges: ["verified"],
    category: "Orphan Care",
    location: "Quetta, Pakistan",
    description:
      "Nutritious daily meals and care for 200 orphaned children for the next three months.",
    zakatEligible: true,
    recurringEnabled: true,
    monthlyImpact: "Feeds one orphan every day for a month",
    story: [
      "200 children at our Quetta shelter have lost one or both parents. For them, this shelter is home — and a warm meal is not always guaranteed.",
      "Your donation provides three nutritious meals a day, along with medical care and a safe place to sleep, for the next three months.",
      "These children deserve more than survival. With your help we can give them nourishment, dignity, and the warmth of belonging.",
    ],
    image: null,
    gradient: "from-violet-500 via-purple-600 to-indigo-700",
    raised: 640_000,
    goal: 1_000_000,
    supporters: 289,
    daysLeft: 21,
    milestones: [
      {
        id: "m1",
        label: "Month 1 meals for all 200 children",
        amountReleased: 180_000,
        reached: true,
        date: "May 1, 2026",
      },
      {
        id: "m2",
        label: "Month 2 meals + medical checkups",
        amountReleased: 200_000,
        reached: true,
        date: "Jun 1, 2026",
      },
      {
        id: "m3",
        label: "Month 3 meals + clothing",
        amountReleased: 220_000,
        reached: false,
      },
    ],
    updates: [
      {
        id: "u1",
        date: "May 5, 2026",
        title: "Month 1 meals delivered — all 200 children fed",
        description:
          "Alhamdulillah, the first month of the meal programme is complete. Three nutritious meals were served every day to all 200 children. We have attached the kitchen purchase receipts, attendance register and photos from the dining hall.",
        amountSpent: 180_000,
        receiptCount: 4,
        photoCount: 6,
        status: "approved",
        photoGradients: [
          "from-violet-400 to-purple-600",
          "from-purple-300 to-indigo-500",
          "from-fuchsia-400 to-violet-600",
        ],
      },
      {
        id: "u2",
        date: "Jun 3, 2026",
        title: "Month 2 complete — medical checkups done for all children",
        description:
          "Second month of meals complete. We also used a portion of this release for a full medical checkup camp — a doctor visited the shelter and screened all 200 children. 12 children were referred for follow-up treatment. All receipts and the doctor's report are uploaded.",
        amountSpent: 200_000,
        receiptCount: 5,
        photoCount: 8,
        status: "approved",
        photoGradients: [
          "from-indigo-400 to-blue-600",
          "from-violet-300 to-purple-500",
          "from-purple-400 to-fuchsia-600",
        ],
      },
    ],
  },
  {
    id: "rebuild-home-swat",
    type: "individual",
    title: "Rebuild Our Home Destroyed by Landslide",
    organizer: "Asif Ur Rehman",
    organizerNote: "Father of 4 • Swat",
    verified: true,
    verificationLevel: "cnic",
    badges: ["trending"],
    category: "Shelter",
    location: "Swat, Pakistan",
    description:
      "A landslide took everything we had. Help us rebuild a safe roof for my four children before winter.",
    zakatEligible: true,
    story: [
      "Last month a landslide swept away the home I built over fifteen years. My four children and I now shelter with relatives in a single cramped room.",
      "Winter in Swat is harsh and unforgiving. I need to rebuild a small, safe house before the snow arrives, but as a farmer I have no savings left.",
      "With your help I can buy materials and rebuild a roof over my children's heads. I will do all the labour myself — I just need a chance.",
    ],
    image: null,
    gradient: "from-stone-400 via-amber-600 to-orange-700",
    raised: 320_000,
    goal: 850_000,
    supporters: 118,
    daysLeft: 15,
    milestones: [
      {
        id: "m1",
        label: "Materials purchased — bricks, cement, timber",
        amountReleased: 150_000,
        reached: true,
        date: "Jun 5, 2026",
      },
      {
        id: "m2",
        label: "Foundation and walls completed",
        amountReleased: 300_000,
        reached: false,
      },
      {
        id: "m3",
        label: "Roof, doors and windows — house complete",
        amountReleased: 200_000,
        reached: false,
      },
    ],
    updates: [
      {
        id: "u1",
        date: "Jun 5, 2026",
        title: "Materials purchased from local supplier — receipts uploaded",
        description:
          "I bought all the foundational materials — bricks, cement, iron rods and timber — from a supplier in Mingora. My brother-in-law helped transport them to the plot. Everything is on site and work begins tomorrow morning, insha'Allah.",
        amountSpent: 150_000,
        receiptCount: 3,
        photoCount: 4,
        status: "approved",
        photoGradients: [
          "from-amber-400 to-orange-600",
          "from-stone-400 to-amber-600",
          "from-orange-300 to-red-500",
        ],
      },
      {
        id: "u2",
        date: "Jun 14, 2026",
        title: "Foundation laid — work is progressing well",
        description:
          "The foundation trench is dug and filled. Three local masons are working every day. My children come to watch and it gives me so much strength. Sharing photos of the foundation work.",
        receiptCount: 1,
        photoCount: 5,
        status: "pending",
        photoGradients: [
          "from-amber-500 to-yellow-600",
          "from-stone-500 to-orange-700",
        ],
      },
    ],
  },
  {
    id: "winter-blankets",
    type: "ngo",
    title: "5,000 Winter Blankets for the Homeless",
    organizer: "Alkhidmat Relief",
    organizerNote: "Verified NGO",
    verified: true,
    verificationLevel: "ngo",
    badges: ["urgent"],
    category: "Emergency Aid",
    location: "Islamabad, Pakistan",
    description:
      "Warm blankets and winter kits for people sleeping rough as temperatures drop below freezing.",
    zakatEligible: true,
    story: [
      "As temperatures in Islamabad and Rawalpindi drop below freezing, hundreds of people sleeping on the streets face deadly cold every night.",
      "Each winter kit includes a thick wool blanket, warm clothing and a pair of socks — small comforts that can save a life on a freezing night.",
      "Help us reach 5,000 people before the coldest weeks of the year. No one should freeze to death for the want of a blanket.",
    ],
    image: null,
    gradient: "from-cyan-400 via-sky-500 to-blue-600",
    raised: 480_000,
    goal: 750_000,
    supporters: 201,
    daysLeft: 9,
    milestones: [
      {
        id: "m1",
        label: "First 2,000 kits procured and distributed",
        amountReleased: 200_000,
        reached: true,
        date: "Dec 2, 2025",
      },
      {
        id: "m2",
        label: "2,000 more kits — remote areas of Rawalpindi",
        amountReleased: 200_000,
        reached: true,
        date: "Dec 10, 2025",
      },
      {
        id: "m3",
        label: "Final 1,000 kits to street sleepers in Islamabad",
        amountReleased: 100_000,
        reached: false,
      },
    ],
    updates: [
      {
        id: "u1",
        date: "Dec 2, 2025",
        title: "2,000 winter kits distributed at I-8 Markaz camp",
        description:
          "Our volunteers distributed 2,000 blanket kits at the Islamabad camp near I-8 Markaz. Each kit contained a thick wool blanket, a jacket and socks. Distribution was complete before midnight. Receipts from the supplier and distribution photos are uploaded.",
        amountSpent: 200_000,
        receiptCount: 3,
        photoCount: 7,
        status: "approved",
        photoGradients: [
          "from-cyan-400 to-sky-600",
          "from-blue-400 to-indigo-600",
          "from-sky-300 to-blue-500",
        ],
      },
      {
        id: "u2",
        date: "Dec 11, 2025",
        title: "Second batch done — Rawalpindi's underpass communities reached",
        description:
          "Teams covered 14 underpass and roadside communities in Rawalpindi over three nights. 2,000 kits given out. We photographed the recipient communities and obtained a sign-off from the local Union Council representative as additional proof.",
        amountSpent: 200_000,
        receiptCount: 4,
        photoCount: 9,
        status: "approved",
        photoGradients: [
          "from-teal-400 to-cyan-600",
          "from-sky-400 to-blue-600",
          "from-cyan-300 to-teal-500",
        ],
      },
      {
        id: "u3",
        date: "Jun 16, 2026",
        title: "Final 1,000 kits planned — reaching last communities this week",
        description:
          "The last batch of 1,000 kits is ready at the warehouse. We will distribute them to the remaining street communities over the next 3 nights. This will complete the full 5,000 target. Final proof update to follow.",
        receiptCount: 1,
        photoCount: 2,
        status: "pending",
        photoGradients: [
          "from-sky-400 to-cyan-600",
        ],
      },
    ],
  },
  {
    id: "cancer-treatment-bilal",
    type: "individual",
    title: "Help Bilal Beat Blood Cancer",
    organizer: "Bilal Ahmed",
    organizerNote: "Patient • Faisalabad",
    verified: true,
    verificationLevel: "cnic",
    badges: ["urgent", "trending"],
    category: "Healthcare",
    location: "Faisalabad, Pakistan",
    description:
      "I was diagnosed with leukemia at 22. Chemotherapy is expensive and I need your help to survive.",
    zakatEligible: true,
    story: [
      "At 22, just as my life was beginning, I was diagnosed with leukemia. The news shattered my family and put my studies on hold.",
      "Doctors say my chances are good if I complete the full course of chemotherapy — but each cycle costs more than my family earns in months.",
      "I am not ready to give up. With your support I can finish my treatment, return to university, and one day give back to others fighting the same battle.",
    ],
    image: null,
    gradient: "from-red-400 via-rose-500 to-pink-600",
    raised: 2_700_000,
    goal: 3_500_000,
    supporters: 1_204,
    daysLeft: 11,
    milestones: [
      {
        id: "m1",
        label: "Cycle 1 chemotherapy — 3 sessions",
        amountReleased: 800_000,
        reached: true,
        date: "Mar 15, 2026",
      },
      {
        id: "m2",
        label: "Cycle 2 chemotherapy + bone marrow biopsy",
        amountReleased: 900_000,
        reached: true,
        date: "May 2, 2026",
      },
      {
        id: "m3",
        label: "Cycle 3 (final) chemotherapy + discharge",
        amountReleased: 1_100_000,
        reached: false,
      },
    ],
    updates: [
      {
        id: "u1",
        date: "Mar 20, 2026",
        title: "Cycle 1 complete — doctors say the cancer is responding",
        description:
          "I finished the first three chemo sessions at Allied Hospital Faisalabad. The oncologist confirmed the cancer cells are responding to treatment. I lost a lot of weight and hair but I am still fighting. Hospital receipts, lab reports and discharge summary uploaded.",
        amountSpent: 800_000,
        receiptCount: 6,
        photoCount: 4,
        status: "approved",
        photoGradients: [
          "from-rose-400 to-pink-600",
          "from-red-300 to-rose-500",
          "from-pink-400 to-fuchsia-600",
        ],
      },
      {
        id: "u2",
        date: "May 8, 2026",
        title: "Cycle 2 done — bone marrow test shows significant improvement",
        description:
          "Cycle 2 is behind me. The bone marrow biopsy results came back and the oncologist used the word 'remission' for the first time. I cried when I read the report. One more cycle to go and I may be declared cancer-free, insha'Allah. Sharing all hospital documents.",
        amountSpent: 900_000,
        receiptCount: 7,
        photoCount: 3,
        status: "approved",
        photoGradients: [
          "from-red-400 to-rose-600",
          "from-rose-300 to-red-500",
        ],
      },
      {
        id: "u3",
        date: "Jun 14, 2026",
        title: "Final cycle scheduled for next week — please keep me in your duas",
        description:
          "Doctors have scheduled my third and final chemo cycle for June 20. I am nervous but hopeful. Your support has given me a second chance at life that I will never forget. Please keep me in your duas.",
        receiptCount: 1,
        photoCount: 2,
        status: "pending",
        photoGradients: [
          "from-pink-300 to-rose-500",
        ],
      },
    ],
  },
  {
    id: "water-well-tharparkar",
    type: "ngo",
    title: "Build a Water Well for a Thar Village",
    organizer: "Al-Khidmat Foundation",
    organizerNote: "Verified NGO",
    verified: true,
    verificationLevel: "ngo",
    badges: ["trending"],
    category: "Water & Sanitation",
    location: "Tharparkar, Pakistan",
    description:
      "A deep-bore well that gives a whole village clean water for decades — Sadaqah Jariyah that flows long after you.",
    zakatEligible: false,
    sadaqahJariyah: true,
    story: [
      "In the Thar desert, women and children walk hours every day to fetch water that is often dirty and unsafe. Waterborne illness is one of the leading causes of child death in the region.",
      "A single deep-bore well with a hand pump and storage tank serves an entire village — roughly 60 households — for decades. It transforms daily life overnight.",
      "This is Sadaqah Jariyah in its purest form: every glass of water drunk, every meal cooked, every ablution made will continue earning reward for you, by the will of Allah, long after the well is built.",
    ],
    image: null,
    gradient: "from-sky-400 via-cyan-500 to-teal-600",
    raised: 360_000,
    goal: 600_000,
    supporters: 174,
    daysLeft: 40,
    milestones: [
      {
        id: "m1",
        label: "Site survey & water table testing",
        note: "Hydrology survey to locate the aquifer",
        amountReleased: 60_000,
        reached: true,
        date: "Jun 1, 2026",
      },
      {
        id: "m2",
        label: "Drilling & casing",
        note: "Deep bore down to the water table",
        reached: false,
      },
      {
        id: "m3",
        label: "Hand pump, storage tank & handover",
        note: "Plaque installed in the donor's chosen name",
        reached: false,
      },
    ],
    updates: [
      {
        id: "u1",
        date: "Jun 1, 2026",
        title: "Site surveyed and water table confirmed",
        description:
          "Our hydrology team surveyed the village and confirmed a reliable water table at 180 feet. The village committee has allocated land for the well and signed an agreement to maintain it. Survey report and land agreement are attached.",
        amountSpent: 60_000,
        receiptCount: 2,
        photoCount: 5,
        status: "approved",
        photoGradients: [
          "from-sky-400 to-cyan-600",
          "from-amber-300 to-orange-500",
        ],
      },
    ],
  },
  {
    id: "hifz-sponsorship",
    type: "ngo",
    title: "Sponsor a Hifz Student for a Year",
    organizer: "Jamia Education Trust",
    organizerNote: "Verified NGO",
    verified: true,
    verificationLevel: "ngo",
    badges: [],
    category: "Mosque & Madrassah",
    location: "Peshawar, Pakistan",
    description:
      "Cover the boarding, meals and education of a child memorising the Holy Quran — Sadaqah Jariyah that never ends.",
    zakatEligible: true,
    sadaqahJariyah: true,
    recurringEnabled: true,
    monthlyImpact: "Covers a Hifz student's boarding & meals for a month",
    story: [
      "Many bright children from low-income families dream of memorising the entire Holy Quran but cannot afford the boarding, food and books a Hifz programme requires.",
      "Your sponsorship covers one student's full year — a safe place to live, three meals a day, books and qualified teachers — so they can devote themselves to becoming a Hafiz-e-Quran.",
      "It is said that the one who supports a Hafiz shares in the immense reward of every verse they recite for the rest of their life. This is Sadaqah Jariyah that compounds forever.",
    ],
    image: null,
    gradient: "from-emerald-500 via-green-600 to-teal-700",
    raised: 540_000,
    goal: 1_200_000,
    supporters: 312,
    daysLeft: 50,
    milestones: [
      {
        id: "m1",
        label: "Semester 1 — fees, boarding & meals",
        amountReleased: 270_000,
        reached: true,
        date: "Jan 15, 2026",
      },
      {
        id: "m2",
        label: "Semester 2 mid-year review & continued sponsorship",
        amountReleased: 270_000,
        reached: true,
        date: "Apr 10, 2026",
      },
      {
        id: "m3",
        label: "Full year complete — Hifz progress certificate",
        amountReleased: 200_000,
        reached: false,
      },
    ],
    updates: [
      {
        id: "u1",
        date: "Jan 18, 2026",
        title: "15 students enrolled and settled in — Semester 1 begins",
        description:
          "We enrolled 15 sponsored Hifz students for the new academic term. All students have been assigned rooms, given their books and introduced to their Ustaads. Admission fee receipts and enrollment register uploaded.",
        amountSpent: 270_000,
        receiptCount: 4,
        photoCount: 5,
        status: "approved",
        photoGradients: [
          "from-emerald-400 to-teal-600",
          "from-green-300 to-emerald-500",
          "from-teal-400 to-cyan-600",
        ],
      },
      {
        id: "u2",
        date: "Apr 12, 2026",
        title: "Mid-year review: 11 students have completed 10+ Juz",
        description:
          "Alhamdulillah, the mid-year assessment results are in. 11 of our 15 students have memorised more than 10 Juz of the Holy Quran in just one semester. Three students have completed their 15th Juz. Sharing the progress certificates and teacher's report.",
        amountSpent: 270_000,
        receiptCount: 3,
        photoCount: 6,
        status: "approved",
        photoGradients: [
          "from-green-400 to-teal-600",
          "from-emerald-300 to-green-500",
          "from-teal-300 to-emerald-600",
        ],
      },
    ],
  },
  {
    id: "plant-trees-pakistan",
    type: "ngo",
    title: "Plant 5,000 Trees Across Pakistan",
    organizer: "Green Pakistan Initiative",
    organizerNote: "Verified NGO",
    verified: true,
    verificationLevel: "ngo",
    badges: [],
    category: "Environment",
    location: "Nationwide, Pakistan",
    description:
      "Every tree cleans the air, shades a street and feeds the soil for generations — a living, breathing Sadaqah Jariyah.",
    zakatEligible: false,
    sadaqahJariyah: true,
    story: [
      "Pakistan is among the countries worst hit by climate change — rising heat, shrinking forests and choking smog threaten millions.",
      "Each donation plants and protects native trees in schools, roadsides and barren land, with two years of care to ensure they survive and thrive.",
      "The Prophet ﷺ said that whenever a Muslim plants a tree and a person, bird or animal eats from it, it is counted as charity. Every tree you fund keeps giving for generations.",
    ],
    image: null,
    gradient: "from-lime-500 via-green-600 to-emerald-700",
    raised: 180_000,
    goal: 500_000,
    supporters: 96,
    daysLeft: 60,
    milestones: [
      {
        id: "m1",
        label: "First 1,500 saplings planted — Lahore & Islamabad",
        amountReleased: 90_000,
        reached: true,
        date: "May 20, 2026",
      },
      {
        id: "m2",
        label: "2,500 more trees — Karachi coastal belt & Peshawar",
        amountReleased: 150_000,
        reached: false,
      },
      {
        id: "m3",
        label: "Final 1,000 trees + 2-year survival audit",
        amountReleased: 100_000,
        reached: false,
      },
    ],
    updates: [
      {
        id: "u1",
        date: "May 22, 2026",
        title: "1,500 saplings planted across 6 schools in Lahore & Islamabad",
        description:
          "Our volunteer teams planted 1,500 native saplings — neem, sheesham and jamun — in schoolyards and roadsides across Lahore and Islamabad. Each sapling is GPS-tagged for our 2-year survival audit. Nursery purchase receipts and planting photos are attached.",
        amountSpent: 90_000,
        receiptCount: 3,
        photoCount: 8,
        status: "approved",
        photoGradients: [
          "from-lime-400 to-green-600",
          "from-green-300 to-emerald-500",
          "from-emerald-400 to-teal-600",
          "from-lime-300 to-green-500",
        ],
      },
      {
        id: "u2",
        date: "Jun 10, 2026",
        title: "One-month survival check — 97% of planted trees are healthy",
        description:
          "We conducted a one-month follow-up check on all 1,500 saplings. 97% are healthy and growing well. The remaining 45 were replaced free of charge by the nursery under our contract. Sharing the check report and photos.",
        receiptCount: 1,
        photoCount: 5,
        status: "approved",
        photoGradients: [
          "from-green-400 to-lime-600",
          "from-emerald-300 to-green-500",
        ],
      },
    ],
  },
];

export function getCampaign(id: string): Campaign | undefined {
  return CAMPAIGNS.find((c) => c.id === id);
}

const DONOR_POOL: Donor[] = [
  { name: "Ahmed R.", amount: 5_000, timeAgo: "2 minutes ago", message: "May Allah ease their hardship. Ameen." },
  { name: "Anonymous", amount: 25_000, timeAgo: "18 minutes ago", anonymous: true },
  { name: "Sana Malik", amount: 2_500, timeAgo: "41 minutes ago", message: "Small contribution, big prayers." },
  { name: "Usman Tariq", amount: 10_000, timeAgo: "1 hour ago" },
  { name: "Ayesha K.", amount: 1_000, timeAgo: "2 hours ago", message: "Sharing with my family too." },
  { name: "Anonymous", amount: 50_000, timeAgo: "3 hours ago", anonymous: true, message: "From our company's CSR fund." },
  { name: "Bilal Sheikh", amount: 7_500, timeAgo: "5 hours ago" },
  { name: "Hina Farooq", amount: 3_000, timeAgo: "7 hours ago", message: "Stay strong!" },
  { name: "Zain Abbas", amount: 15_000, timeAgo: "9 hours ago" },
  { name: "Maryam J.", amount: 2_000, timeAgo: "12 hours ago", message: "Praying for a quick recovery." },
  { name: "Anonymous", amount: 4_500, timeAgo: "1 day ago", anonymous: true },
  { name: "Hamza Iqbal", amount: 20_000, timeAgo: "1 day ago", message: "Donated my Zakat here. JazakAllah." },
];

/** Deterministic recent-donor list for a campaign. */
export function getDonors(campaignId: string, count = 8): Donor[] {
  let seed = 0;
  for (const ch of campaignId) seed += ch.charCodeAt(0);
  const offset = seed % DONOR_POOL.length;
  const rotated = [...DONOR_POOL.slice(offset), ...DONOR_POOL.slice(0, offset)];
  return rotated.slice(0, count);
}
